export default {
	id: 'anthropology',
	name: 'Anthropology',
	key: 'Si♭',
	sections: [
		{
			name: 'A',
			chords: [
				{ bar: 1, root: 'Si♭', quality: '', extensions: 'Δ' },
				{ root: 'Sol', quality: '', extensions: '7' },
				{ bar: 2, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 3, root: 'Re', quality: '-', extensions: '7' },
				{ root: 'Sol', quality: '', extensions: '7' },
				{ bar: 4, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 5, root: 'Fa', quality: '-', extensions: '7' },
				{ root: 'Si♭', quality: '', extensions: '7' },
				{ bar: 6, root: 'Mi♭', quality: '', extensions: 'Δ' },
				{ root: 'La♭', quality: '', extensions: '7' },
				{ bar: 7, root: 'Re', quality: '-', extensions: '7' },
				{ root: 'Sol', quality: '', extensions: '7' },
				{ bar: 8, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
			],
		},
		{
			name: 'A',
			chords: [
				{ bar: 9, root: 'Si♭', quality: '', extensions: 'Δ' },
				{ root: 'Sol', quality: '', extensions: '7' },
				{ bar: 10, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 11, root: 'Re', quality: '-', extensions: '7' },
				{ root: 'Sol', quality: '', extensions: '7' },
				{ bar: 12, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 13, root: 'Fa', quality: '-', extensions: '7' },
				{ root: 'Si♭', quality: '', extensions: '7' },
				{ bar: 14, root: 'Mi♭', quality: '', extensions: 'Δ' },
				{ root: 'La♭', quality: '', extensions: '7' },
				{ bar: 15, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 16, root: 'Si♭', quality: '', extensions: 'Δ' },
			],
		},
		{
			name: 'B',
			chords: [
				{ bar: 17, root: 'Re', quality: '', extensions: '7' },
				{ bar: 18, root: 'Re', quality: '', extensions: '7' },
				{ bar: 19, root: 'Sol', quality: '', extensions: '7' },
				{ bar: 20, root: 'Sol', quality: '', extensions: '7' },
				{ bar: 21, root: 'Do', quality: '', extensions: '7' },
				{ bar: 22, root: 'Do', quality: '', extensions: '7' },
				{ bar: 23, root: 'Fa', quality: '', extensions: '7' },
				{ bar: 24, root: 'Fa', quality: '', extensions: '7' },
			],
		},
		{
			name: 'A',
			chords: [
				{ bar: 25, root: 'Si♭', quality: '', extensions: 'Δ' },
				{ root: 'Sol', quality: '', extensions: '7' },
				{ bar: 26, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 27, root: 'Re', quality: '-', extensions: '7' },
				{ root: 'Sol', quality: '', extensions: '7' },
				{ bar: 28, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 29, root: 'Fa', quality: '-', extensions: '7' },
				{ root: 'Si♭', quality: '', extensions: '7' },
				{ bar: 30, root: 'Mi♭', quality: '', extensions: 'Δ' },
				{ root: 'La♭', quality: '', extensions: '7' },
				{ bar: 31, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 32, root: 'Si♭', quality: '', extensions: 'Δ' },
			],
		},
	],
};
