export default {
	id: 'lullaby-of-birdland',
	name: 'Lullaby of Birdland',
	key: 'Si♭',
	sections: [
		{
			name: 'A',
			chords: [
				{ bar: 1, root: 'Sol', quality: '-', extensions: '' },
				{ root: 'Mi', quality: 'ø', extensions: '7' },
				{ bar: 2, root: 'La', quality: '', extensions: '7' },
				{ root: 'Re', quality: '', extensions: '7' },
				{ bar: 3, root: 'Sol', quality: '-', extensions: '' },
				{ root: 'Sol', quality: '-', extensions: '' },
				{ bar: 4, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 5, root: 'Re', quality: '-', extensions: '7' },
				{ root: 'Sol', quality: '-', extensions: '7' },
				{ bar: 6, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 7, root: 'Si♭', quality: '', extensions: 'Δ' },
				{ root: 'Si♭', quality: '', extensions: 'Δ' },
				{ bar: 8, root: 'La', quality: 'ø', extensions: '7' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
			],
		},
		{
			name: 'B',
			chords: [
				{ bar: 1, root: 'Re', quality: 'ø', extensions: '7' },
				{ root: 'Sol', quality: '', extensions: '7♭9' },
				{ bar: 2, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Do', quality: '-', extensions: '7' },
				{ bar: 3, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7♭9' },
				{ bar: 4, root: 'Si♭', quality: '', extensions: 'Δ' },
				{ root: 'Si♭', quality: '', extensions: 'Δ' },
				{ bar: 5, root: 'Re', quality: 'ø', extensions: '7' },
				{ root: 'Sol', quality: '', extensions: '7♭9' },
				{ bar: 6, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Do', quality: '-', extensions: '7' },
				{ bar: 7, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7♭9' },
				{ bar: 8, root: 'Si♭', quality: '', extensions: 'Δ' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
			],
		},
	],
};
