export default {
	id: 'my-one-and-only-love',
	name: 'My One and Only Love',
	key: 'Re',
	sections: [
		{
			name: 'A',
			chords: [
				{ bar: 1, root: 'Re', quality: '', extensions: 'Δ' },
				{ root: 'Si', quality: '-', extensions: '7' },
				{ bar: 2, root: 'Mi', quality: '-', extensions: '7' },
				{ root: 'La', quality: '', extensions: '7' },
				{ root: 'Si♭', quality: 'o', extensions: '' },
				{ bar: 3, root: 'Si', quality: '-', extensions: '7' },
				{ root: 'Sol', quality: '', extensions: 'Δ' },
				{ bar: 4, root: 'Fa♯', quality: '-', extensions: '7' },
				{ root: 'Si', quality: '', extensions: '7' },
				{ bar: 5, root: 'Mi', quality: '-', extensions: '7' },
				{ root: 'La', quality: '', extensions: '7' },
				{ root: 'Si♭', quality: 'o', extensions: '' },
				{ bar: 6, root: 'Si', quality: '-', extensions: '7' },
				{ root: 'Mi', quality: '', extensions: '7' },
				{ bar: 7, root: 'Mi', quality: '-', extensions: '7' },
				{ root: 'La', quality: '', extensions: '7' },
				{ bar: 8, root: 'Fa♯', quality: '-', extensions: '7' },
				{ root: 'Si', quality: '', extensions: '7' },
				{ root: 'Mi', quality: '-', extensions: '7' },
				{ root: 'La', quality: '', extensions: '7' },
			],
		},
		{
			name: 'A (2)',
			chords: [
				{ bar: 1, root: 'Re', quality: '', extensions: 'Δ' },
				{ root: 'Si', quality: '-', extensions: '7' },
				{ bar: 2, root: 'Mi', quality: '-', extensions: '7' },
				{ root: 'La', quality: '', extensions: '7' },
				{ root: 'Si♭', quality: 'o', extensions: '' },
				{ bar: 3, root: 'Si', quality: '-', extensions: '7' },
				{ root: 'Sol', quality: '', extensions: 'Δ' },
				{ bar: 4, root: 'Fa♯', quality: '-', extensions: '7' },
				{ root: 'Si', quality: '', extensions: '7' },
				{ bar: 5, root: 'Mi', quality: '-', extensions: '7' },
				{ root: 'La', quality: '', extensions: '7' },
				{ root: 'Si♭', quality: 'o', extensions: '' },
				{ bar: 6, root: 'Si', quality: '-', extensions: '7' },
				{ root: 'Mi', quality: '', extensions: '7' },
				{ bar: 7, root: 'Mi', quality: '-', extensions: '7' },
				{ root: 'La', quality: '', extensions: '7' },
				{ bar: 8, root: 'Re', quality: '', extensions: '6' },
				{ root: 'Sol♯', quality: 'ø', extensions: '7' },
				{ root: 'Do♯', quality: '', extensions: '7' },
			],
		},
		{
			name: 'B',
			chords: [
				{ bar: 1, root: 'Fa♯', quality: '-', extensions: '7' },
				{ bar: 2, root: 'Sol♯', quality: 'ø', extensions: '7' },
				{ root: 'Do♯', quality: '', extensions: '7♭9' },
				{ bar: 3, root: 'Fa♯', quality: '-', extensions: '7' },
				{ bar: 4, root: 'Sol♯', quality: 'ø', extensions: '7' },
				{ root: 'Do♯', quality: '', extensions: '7♭9' },
				{ bar: 5, root: 'Fa♯', quality: '-', extensions: '' },
				{ root: 'Fa♯', quality: '-', extensions: 'Δ' },
				{ bar: 6, root: 'Fa♯', quality: '-', extensions: '7' },
				{ root: 'Si', quality: '', extensions: '7' },
				{ bar: 7, root: 'Mi', quality: '-', extensions: '7' },
				{ root: 'Si', quality: '', extensions: '7' },
				{ bar: 8, root: 'Mi', quality: '-', extensions: '7' },
				{ root: 'La', quality: '', extensions: '7' },
			],
		},
	],
};
