export default {
	id: 'stella-by-stalight',
	name: 'Stella by Starlight',
	key: 'Do',
	sections: [
		{
			name: 'A',
			chords: [
				{ bar: 1, root: 'Fa♯', quality: 'ø', extensions: '7' },
				{ bar: 2, root: 'Si', quality: '', extensions: '7♭9' },
				{ bar: 3, root: 'Re', quality: '-', extensions: '7' },
				{ bar: 4, root: 'Sol', quality: '', extensions: '7' },
				{ bar: 5, root: 'Sol', quality: '-', extensions: '7' },
				{ bar: 6, root: 'Do', quality: '', extensions: '7' },
				{ bar: 7, root: 'Fa', quality: '', extensions: 'Δ' },
				{ bar: 8, root: 'Si♭', quality: '', extensions: '7' },
				{ bar: 9, root: 'C', quality: '', extensions: 'Δ' },
				{ bar: 10, root: 'Fa♯', quality: 'ø', extensions: '7' },
				{ root: 'Si', quality: '', extensions: '7♭9' },
				{ bar: 11, root: 'Mi', quality: '-', extensions: '7' },
				{ bar: 12, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 13, root: 'Sol', quality: '', extensions: 'Δ' },
				{ bar: 14, root: 'Fa♯', quality: 'ø', extensions: '7' },
				{ bar: 15, root: 'Fa♯', quality: '', extensions: 'Δ♯11' },
				{ bar: 16, root: 'Mi', quality: '', extensions: '7♭9' },
			],
		},
		{
			name: 'B',
			chords: [
				{ bar: 1, root: 'La', quality: '', extensions: '7♭13' },
				{ bar: 2, root: 'La', quality: '', extensions: '7♭13' },
				{ bar: 3, root: 'Re', quality: '-', extensions: '7' },
				{ bar: 4, root: 'Re', quality: '-', extensions: '7' },
				{ bar: 5, root: 'Si♭', quality: '', extensions: '7♯11' },
				{ bar: 6, root: 'Si♭', quality: '', extensions: '7♯11' },
				{ bar: 7, root: 'Do', quality: '', extensions: 'Δ' },
				{ bar: 8, root: 'Do', quality: '', extensions: 'Δ' },
			],
		},
		{
			name: 'C',
			chords: [
				{ bar: 1, root: 'Fa♯', quality: 'ø', extensions: '7' },
				{ bar: 2, root: 'Si', quality: '', extensions: '7♭9' },
				{ bar: 3, root: 'Mi', quality: 'ø', extensions: '7' },
				{ bar: 4, root: 'La', quality: '', extensions: '7♭9' },
				{ bar: 5, root: 'Re', quality: 'ø', extensions: '7' },
				{ bar: 6, root: 'Sol', quality: '', extensions: '7♭9' },
				{ bar: 7, root: 'Do', quality: '', extensions: 'Δ' },
				{ bar: 8, root: 'Do', quality: '', extensions: 'Δ' },
			],
		},
	],
};
