export default {
	id: 'you-dont-know-what-love-is',
	name: 'You Don’t Know What Love Is',
	key: 'Si♭',
	sections: [
		{
			name: 'A',
			chords: [
				{ bar: 1, root: 'Sol', quality: '-', extensions: '7' },
				{ bar: 2, root: 'Mi♭', quality: '', extensions: '9' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
				{ bar: 3, root: 'Sol', quality: '-', extensions: '6' },
				{ root: 'La', quality: '-', extensions: '7' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
				{ bar: 4, root: 'Mi♭', quality: '', extensions: '7' },
				{ bar: 5, root: 'Do', quality: '', extensions: '7' },
				{ root: 'La', quality: '-', extensions: '7♭5' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
				{ bar: 6, root: 'Sol', quality: '-', extensions: '7' },
				{ root: 'Si♭', quality: '', extensions: '7' },
				{ bar: 7, root: 'Mi♭', quality: '', extensions: '7' },
				{ bar: 8, root: 'La', quality: '-', extensions: '7♭5' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
			],
		},
		{
			name: 'A',
			chords: [
				{ bar: 9, root: 'Sol', quality: '-', extensions: '7' },
				{ bar: 10, root: 'Mi♭', quality: '', extensions: '9' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
				{ bar: 11, root: 'Sol', quality: '-', extensions: '6' },
				{ root: 'La', quality: '-', extensions: '7' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
				{ bar: 12, root: 'Mi♭', quality: '', extensions: '7' },
				{ bar: 13, root: 'Do', quality: '', extensions: '7' },
				{ root: 'La', quality: '-', extensions: '7♭5' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
				{ bar: 14, root: 'Sol', quality: '-', extensions: '7' },
				{ root: 'Si♭', quality: '', extensions: '7' },
				{ bar: 15, root: 'Mi♭', quality: '', extensions: '7' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
				{ bar: 16, root: 'Sol', quality: '-', extensions: '6' },
			],
		},
		{
			name: 'B',
			chords: [
				{ bar: 17, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 18, root: 'Si♭', quality: '', extensions: 'Δ' },
				{ root: 'Sol', quality: '', extensions: '7♭9' },
				{ bar: 19, root: 'Do', quality: '-', extensions: '7' },
				{ root: 'Fa', quality: '', extensions: '7' },
				{ bar: 20, root: 'Si♭', quality: '', extensions: 'Δ' },
				{ bar: 21, root: 'Mi', quality: '-', extensions: '7' },
				{ root: 'La', quality: '', extensions: '7' },
				{ bar: 22, root: 'Re', quality: '', extensions: 'Δ' },
				{ bar: 23, root: 'Mi♭', quality: '', extensions: '9(♯11)' },
				{ bar: 24, root: 'Re', quality: '', extensions: '7♭9' },
			],
		},
		{
			name: 'A',
			chords: [
				{ bar: 25, root: 'Sol', quality: '-', extensions: '7' },
				{ bar: 26, root: 'Mi♭', quality: '', extensions: '9' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
				{ bar: 27, root: 'Sol', quality: '-', extensions: '6' },
				{ root: 'La', quality: '-', extensions: '7' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
				{ bar: 28, root: 'Mi♭', quality: '', extensions: '7' },
				{ bar: 29, root: 'Do', quality: '', extensions: '7' },
				{ root: 'La', quality: '-', extensions: '7♭5' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
				{ bar: 30, root: 'Sol', quality: '-', extensions: '7' },
				{ root: 'Si♭', quality: '', extensions: '7' },
				{ bar: 31, root: 'Mi♭', quality: '', extensions: '7' },
				{ root: 'Re', quality: '', extensions: '7♭9' },
				{ bar: 32, root: 'Sol', quality: '-', extensions: '6' },
			],
		},
	],
};
